# Nginx Virtual Host: nurulwafa.ruangtech.com & mnurulwafa.ruangtech.com
# Path: /etc/nginx/sites-available/nurulwafa.ruangtech.com

server {
    listen 80;
    server_name nurulwafa.ruangtech.com mnurulwafa.ruangtech.com;

    # Client body limit untuk upload berkas/foto
    client_max_body_size 20M;

    # Reverse proxy ke Node Express (port 5011)
    location / {
        proxy_pass http://127.0.0.1:5011;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
